### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by BoheSama1999** [pierre-josselin/payday-2-ultimate-trainer-6#104]
```
PAYDAY 2 - Ultimate Trainer 6

--- INSTALLATION ---

Creating environment file... OK
Creating config file... OK
Installing project (http-server)... OK
Installing application... OK
Building application...

An error has occurred:

Command failed: cd "E:\SteamLibrary\steamapps\common\PAYDAY 2\mods\payday-2-ultimate-trainer-6-main\payday-2-ultimate-trainer-6-app" && npm run build
[commonjs--resolver] Failed to resolve entry for package "mdurl". The package may have incorrect main/module/exports specified in its package.json.
file: E:/SteamLibrary/steamapps/common/PAYDAY 2/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/markdown-it/index.js
error during build:
Error: Failed to resolve entry for package "mdurl". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
    at resolvePackageEntry (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
    at tryNodeResolve (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
    at Object.resolveId (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
    at file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:24899:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:24799:28)
    at async resolveId (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:23480:26)
    at async ModuleLoader.resolveId (file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:23893:15)
    at async file:///E:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:8187:16
    at async Promise.all (index 7)
```

**Comment by pierre-josselin** [comment]
Hi, you can find already installed versions here:

https://drive.google.com/drive/folders/1ii6VwSu2ezoerXJ5Ql59apOgWLU-EIR6?usp=drive_link

**Comment by BoheSama1999** [comment]
Thanks
