### ISSUE TITLE
Building Application Issue

### ISSUE THREAD

**Issue by TJenks1308** [pierre-josselin/payday-2-ultimate-trainer-6#64]
I followed the Readme file up to this point for installing UT6, when it starts the building application process, it shows this message:

Command failed: cd "X:\SteamLibrary\steamapps\common\PAYDAY 2\mods\payday-2-ultimate-trainer-6-main\payday-2-ultimate-trainer-6-app" && npm run build

Could not resolve "./modifiers/index.js" from "node_modules/@popperjs/core/lib/index.js"
file: X:/SteamLibrary/steamapps/common/PAYDAY 2/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/@popperjs/core/lib/index.js

error during build:
RollupError: Could not resolve "./modifiers/index.js" from "node_modules/@popperjs/core/lib/index.js"
    at error (file:///X:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:2213:30)
    at ModuleLoader.handleInvalidResolvedId (file:///X:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:24219:24)
    at file:///X:/SteamLibrary/steamapps/common/PAYDAY%202/mods/payday-2-ultimate-trainer-6-main/payday-2-ultimate-trainer-6-app/node_modules/rollup/dist/es/shared/node-entry.js:24181:26

**Comment by pierre-josselin** [comment]
Hi, that's a curious issue.

When 5.3.0 will be released, I will provide an already installed archive for people encountering issues like that.
I will notify you here when it's released!
